INSERT INTO post (title, content) VALUES
    ('Article about Java, Spring, and Cloud', 'Content about Java, Spring, and Cloud'),
    ('Introduction to Spring Boot', 'Content about Spring Boot'),
    ('Cloud Computing Basics', 'Content about Cloud Computing'),
    ('Java Programming Fundamentals', 'Content about Java Programming'),
    ('Getting Started with Spring Security', 'Content about Spring Security'),
    ('Microservices Architecture Overview', 'Content about Microservices Architecture'),
    ('Java 8 Features and Streams', 'Content about Java 8 Features and Streams'),
    ('Spring Data JPA Tutorial', 'Content about Spring Data JPA'),
    ('Cloud-Native Application Development', 'Content about Cloud-Native Development'),
    ('Advanced Java Concepts', 'Content about Advanced Java'),
    ('Deep Dive into Spring Framework', 'Content about in-depth Spring Framework'),
    ('Building Scalable Cloud Applications', 'Content about Scalable Cloud Applications'),
    ('Java Multithreading Techniques', 'Content about Java Multithreading'),
    ('Securing Microservices with OAuth', 'Content about OAuth and Microservices'),
    ('Mastering Spring Boot Configuration', 'Content about Spring Boot Configuration'),
    ('Cloud Storage Solutions for Developers', 'Content about Cloud Storage'),
    ('Exploring Java 9 Modules', 'Content about Java 9 Modules'),
    ('Advanced Spring Security Features', 'Content about Advanced Spring Security'),
    ('Event-Driven Architecture with Spring Kafka', 'Content about Event-Driven Architecture'),
    ('Optimizing Java Code for Performance', 'Content about Java Code Optimization'),
    ('Serverless Computing and its Benefits', 'Content about Serverless Computing'),
    ('Data Encryption in Cloud Applications', 'Content about Data Encryption'),
    ('Java Design Patterns in Practice', 'Content about Java Design Patterns'),
    ('Spring Boot Testing Strategies', 'Content about Spring Boot Testing'),
    ('Developing RESTful APIs with Spring', 'Content about RESTful APIs and Spring');

INSERT INTO tag (name) VALUES
    ('java'),
    ('spring'),
    ('cloud'),
    ('programming'),
    ('security'),
    ('microservices'),
    ('java8'),
    ('jpa'),
    ('cloudnative'),
    ('advanced');

INSERT INTO posts_tags (post_id, tag_id) VALUES
    (1, 1), (1, 2), (1, 3),
    (2, 1), (2, 2),
    (3, 3),
    (4, 1),
    (5, 2), (5, 4),
    (6, 2), (6, 5),
    (7, 1), (7, 6), (7, 7),
    (8, 2), (8, 7), (8, 8),
    (9, 3), (9, 6), (9, 9),
    (10, 1), (10, 10),
    (11, 2), (11, 3),
    (12, 3), (12, 5),
    (13, 1), (13, 2),
    (14, 6), (14, 9),
    (15, 2), (15, 7),
    (16, 1), (16, 8),
    (17, 3), (17, 6),
    (18, 1), (18, 5),
    (19, 2), (19, 7),
    (20, 1), (20, 9),
    (21, 3), (21, 10),
    (22, 2), (22, 7),
    (23, 1), (23, 8),
    (24, 3), (24, 6),
    (25, 1), (25, 4);
